#!/usr/bin/env bash


for x in `find . -maxdepth 1 -type d`; do


  fontdir=$(echo "$x" | cut -d\/ -f2-)

  if [ -n "$(echo $fontdir | grep -Ev '\.|\.\.')" ]; then
    if [ -n "${fontdir}" -a -f "${fontdir}/uninstall"  ]; then

      ## using multiprocessing
      {
      
        for uninstall in `ls "${fontdir}" | grep -i 'uninstall'`; do

          scriptfile="${fontdir}/${uninstall}"
          echo match $scriptfile ...
          bash "${scriptfile}"
        done
      } &
    fi
  fi
done

echo
